using System;
using System.Collections.Generic;

namespace RDCELERP.DAL.Entities
{
    public partial class ZohoExchangeDatum
    {
        public int SponsorDataId { get; set; }
        public bool? IsDataTransfered { get; set; }
        public string? Errorlog { get; set; }
        public string? RegdNo { get; set; }
        public string? SponsorOrderNo { get; set; }
        public string? OrderType { get; set; }
        public string? CustName { get; set; }
        public string? CustEMail { get; set; }
        public string? CustMobile { get; set; }
        public string? CustDeclaredQlty { get; set; }
        public double? BaseExchValueQ { get; set; }
        public string? ExchProdGroup { get; set; }
        public string? OldProdType { get; set; }
        public string? ModelNo { get; set; }
        public string? NewPrice { get; set; }
        public string? InvoiceDate { get; set; }
        public double? Bonus { get; set; }
        public string? ProductGroup { get; set; }
        public string? ProductType { get; set; }
        public string? CustAdd1 { get; set; }
        public string? CustAdd2 { get; set; }
        public double? CustPinCode { get; set; }
        public string? CustCity { get; set; }
        public string? CustState { get; set; }
        public string? Landmark { get; set; }
        public string? NewProdGroup { get; set; }
        public string? NewProdType { get; set; }
        public string? NewBrand { get; set; }
        public string? NewSize { get; set; }
        public string? AbbFees { get; set; }
        public string? EvcStatus { get; set; }
        public string? OrderFlag { get; set; }
        public string? EMailSmsFlag { get; set; }
        public string? QcFlag { get; set; }
        public string? InstallationFlag { get; set; }
        public string? PickupFlag { get; set; }
        public string? PaymentFlag { get; set; }
        public string? EvcDropFlag { get; set; }
        public string? PostingFlag { get; set; }
        public string? AbbPlanName { get; set; }
        public string? AbbPlanPeriodMonths { get; set; }
        public string? Mode { get; set; }
        public string? AmountPayableThroughLgc { get; set; }
        public string? OldBrand { get; set; }
        public DateTime? EstimateDeliveryDate { get; set; }
        public string? LatestStatus { get; set; }
        public string? OrderDate { get; set; }
        public string? PickupDate { get; set; }
        public string? SecondaryOrderFlag { get; set; }
        public string? StatusReason { get; set; }
        public string? ActualAmountPaid { get; set; }
        public DateTime? ExpectedPickupDate { get; set; }
        public string? ActualPickupDate { get; set; }
        public string? LgcTktNo { get; set; }
        public string? Size { get; set; }
        public string? ReadyForLogisticTicket { get; set; }
        public string? AddedTime { get; set; }
        public string? Pic1 { get; set; }
        public string? Pic2 { get; set; }
        public string? Pic3 { get; set; }
        public string? Pic4 { get; set; }
        public string? InvoiceImage { get; set; }
        public string? Id { get; set; }
        public string? IsDeferred { get; set; }
        public string? IsVoucherRedeemed { get; set; }
        public string? VoucherCode { get; set; }
        public string? VoucherRedeemDate { get; set; }
        public string? VoucherAmount { get; set; }
        public string? PurchasedProduct { get; set; }
        public string? PurchasedProductModel { get; set; }
        public string? StoreNameForPurchasedProduct { get; set; }
        public string? LogisticBy { get; set; }
        public string? UploadDateTime { get; set; }
        public string? SponsorName { get; set; }
        public string? AssociateEmail { get; set; }
        public string? StoreStatus { get; set; }
        public string? PurchasedProductCategory { get; set; }
        public string? StoreCode { get; set; }
        public string? AssociateName { get; set; }
        public string? AssociateCode { get; set; }
        public string? StorePhoneNumber { get; set; }
        public string? LastName { get; set; }
        public string? Cust1stName { get; set; }
        public string? CustomerDeclaredAge { get; set; }
        public string? IsDtoC { get; set; }
        public double? BaseExchValueP { get; set; }
        public double? BaseExchValueR { get; set; }
        public double? BaseExchValueS { get; set; }
        public double? EvcP { get; set; }
        public double? EvcQ { get; set; }
        public double? EvcR { get; set; }
        public double? EvcS { get; set; }
        public string? ProdSrNo { get; set; }
        public string? HsnCodeForAbbFees { get; set; }
        public string? InvoiceNo { get; set; }
        public string? PriceStartDate { get; set; }
        public string? PriceEndDate { get; set; }
        public string? Abb { get; set; }
        public string? Exchange { get; set; }
        public string? ExchangeStatus { get; set; }
        public string? SponsorProgCode { get; set; }
        public string? ExchPriceId { get; set; }
        public string? AbbPriceId { get; set; }
        public string? ReasonForCancellation { get; set; }
        public string? FirstAttemptDate { get; set; }
        public string? RecordStatus { get; set; }
        public string? InvoicePosted { get; set; }
        public string? EMailSmsDate { get; set; }
        public string? QcDate { get; set; }
        public string? InstallationDate { get; set; }
        public string? PaymentDate { get; set; }
        public string? EvcDropDate { get; set; }
        public string? PostingDate { get; set; }
        public string? LatestDateTime { get; set; }
        public string? Closed { get; set; }
        public string? SvcSCallNo { get; set; }
        public double? TotalQuoteP { get; set; }
        public double? TotalQuoteQ { get; set; }
        public double? TotalQuoteR { get; set; }
        public double? TotalQuoteS { get; set; }
        public string? ActualType { get; set; }
        public string? ActualBrand { get; set; }
        public string? ProdSrNo1 { get; set; }
        public string? CompressorNoOduSrNo { get; set; }
        public string? PdfFileForQc { get; set; }
        public string? QcComment { get; set; }
        public string? PreferredTimeForQc { get; set; }
        public string? PreferredQcDateAndTime { get; set; }
        public string? ActualSize { get; set; }
        public string? ActualProdQltyAtTimeOfQc { get; set; }
        public string? ActualAge { get; set; }
        public string? ProofOfDelivery { get; set; }
        public string? ActualTotalAmountAsPerQc { get; set; }
        public double? ActualBaseAmountAsPerQc { get; set; }
        public string? ActualEvcAmountAsPerQc { get; set; }
        public string? CustOkForPrice { get; set; }
        public string? LogisticPic1 { get; set; }
        public string? LogisticPic2 { get; set; }
        public string? LogisticPic3 { get; set; }
        public string? LogisticPic4 { get; set; }
        public string? CustDeclaration { get; set; }
        public string? QcByLgcReviseEvcCode { get; set; }
        public string? EvcAcknowledge { get; set; }
        public string? PaymentToCustomer { get; set; }
        public string? LogisticsBonus { get; set; }
        public string? LgcTktCreatedDate { get; set; }
        public double? ActualAmtPayableInclBonus { get; set; }
        public string? BankReference { get; set; }
        public string? DatePaid { get; set; }
        public string? LogisticsStatusRemark { get; set; }
        public string? PickupPriority { get; set; }
        public string? NatureOfComplaint { get; set; }
        public string? IsUnderWarranty { get; set; }
    }
}
